### ISSUE TITLE
HUGE privacy issue with the current version! All prompts are sent to the internet (Duck Duck Go).

### ISSUE THREAD

**Issue by oderwat** [ItsPi3141/alpaca-electron#67]
Running a local LLM model for sure does not mean that people want to send their prompts out to the internet without their consent. This change needs to be communicated ASAP.

**Comment by ItsPi3141** [comment]
The feature is a WIP, I'll add a toggle soon. Relax. I haven't even made a release yet.

**Comment by oderwat** [comment]
Pushing it to GitHub main is making it public. Put it in a branch if you do not plan to have people run into it. That is why such things exist. Closing this issue shows that you do not want people to see it.

**Comment by ItsPi3141** [comment]
> Pushing it to GitHub main is making it public. Put it in a branch if you do not plan to have people run into it. That is why such things exist. Closing this issue shows that you do not want people to see it.

I'll admit I made a mistake. I forgot to push the changes to a different branch. 

I didn't close the issue because I don't want people to see it. I closed it because I don't want it to flood the open issues page. You should start a discussion instead of opening an issue if you want to tell people that there is a privacy concern. 

If you want, I can disable it and create a different branch for the duckduckgo feature. 

----

People who knows what they're doing would look at the code and realize that it's sending requests to duckduckgo. Then, they would disable the feature themselves. 

People who think they know what they're doing but actually don't should not get mad that it's sending their prompts to a search query in duckduckgo. They should know that releases exists for a good reason. 

People who don't know what they're doing at all should just download from release.
