### ISSUE TITLE
[BUG] HTML in prompt is not escaped

### ISSUE THREAD

**Issue by Swallow74** [ItsPi3141/alpaca-electron#68]
HTML code is not escaped. If you paste HTML code into the chat interface, the code is rendered rather than displayed as plain text.

**Comment by ItsPi3141** [comment]
I'll fix that in the next update.

**Comment by ItsPi3141** [comment]
Fixed in https://github.com/ItsPi3141/alpaca-electron/commit/805e8c4bfc78cf241b6a62a8764fa181c9f6fbb5. See [here](https://github.com/ItsPi3141/alpaca-electron/commit/805e8c4bfc78cf241b6a62a8764fa181c9f6fbb5#diff-1b3a93ed16f5deb8d482f3295fc99339adf138e2bf197e65a5fe3964f5e1c93eR185-R189). It will be included in the next release (v1.0.6).
