### ISSUE TITLE
Flagged as a Virus?

### ISSUE THREAD

**Issue by ReconIII** [ItsPi3141/alpaca-electron#9]
My anti-virus and virus total are flagging Apaca Electron
https://www.virustotal.com/gui/file/2d1baa698e96e9257437ca8a72982720620d4c69d55d9ae807fc8628510405a7/details
![image](https://user-images.githubusercontent.com/129114500/228055272-ed5c9f36-e26d-4e8f-9729-388c43fda6d6.png)

**Comment by ItsPi3141** [comment]
Not sure what Trojan.Bulz is. There's no exact description of what Trojan.Bulz actually does. However, I think it could've been flagged because it creates a terminal shell (viruses do that a lot) and runs an executable that uses high amounts of resources. 

If you want, you can go through the source code to make sure there are no malicious code. And then build the app yourself.

**Comment by ItsPi3141** [comment]
Update: I found out that it was because of the Squirrel.Windows installer (strange because it doesnt happen on Discord and GH Desktop). I will probably not switch to another installer because Squirrel.Windows has the easiest installation process right now and doesn't require admin permissions.

**Comment by ReconIII** [comment]
Thanks for the info! I was just curious as to why it was flagged, better to be safe than sorry. Love the program btw, it makes using alpaca so much more user friendly!
